### ISSUE TITLE
Migrate to JavaScript action

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-hugo#20]
It is better to install Hugo with downloading a binary file.

- **Hugo extended** can run on GitHub Actions virtual machine (ubuntu-18.04).
- Thanks to Golang (>=12) is pre-installed, we can use **Hugo Modules**.

## TODO

- [x] Docker to JavaScript
- [x] fix: extended false
- [x] gha: change trigger to `on: push`
- [x] Update README
- [x] Disconnect from Docker Hub.
- [x] update: release note
- [x] Announce to users who use `peaceiris/actions-hugo`
- [x] Update posts (Reddit, Hugo forum, Qiita)

TBD

- Add dump `hugo version` `go version` `git --version` (Go to #23 )
- os option (Go to #24 )
- JavaScript to TypeScript

## References

- [actions/javascript-action](https://github.com/actions/javascript-action)
- [actions/typescript-action](https://github.com/actions/typescript-action)
- [actions/setup-python](https://github.com/actions/setup-python)
